### DISCUSSION TITLE
Google Workspace SMTP relay without authentication

### DISCUSSION THREAD

**Discussion by dodedodo** [padloc/padloc#718] [Support] [answered]
Hi! 

Could you help me configure padloc smtp for google-workspace smtp relay without user authentication?

I'm trying to self-host padloc with docker, but I'm stuck on configuring the SMTP server. Upon first sign-up I get the generic error 

![image](https://github.com/padloc/padloc/assets/3252036/c1442a93-bdee-42c9-bbfc-e7556d1ebc69)

I cannot find any errors or logs besides  ` (node:58) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`

I'm trying to use google workspace as smtp relay. It's configured so that authentication isn't required, but instead the sending IP is checked. 

**What I think is the problem**
I'm not quite sure, but I suspect this is where things go wrong. Looking at [this line](https://github.com/padloc/padloc/blob/30ebb78768d4cfccdbf5f72bd51517c24334f874/packages/server/src/email/smtp.ts#L46)  it looks like user/pass authentication is used when they're both not false. 

**What i've tried**
By omitting the `PL_EMAIL_SMTP_USER` and `PL_EMAIL_SMTP_PASSWORD` env variables from docker-compose, it seems padloc sets them to an empty string (according to the docker stdout `server started with config: {...}`).

While `PL_EMAIL_SMTP_USER=false` seems to be interpreted as the string `"false"` (according to the docker stdout `server started with config: {...}`)

**Here's an excerpt of my configuration**

``` yml
...
services:
    server:
        image: padloc/server
        environment:
            PL_DATA_BACKEND: leveldb
            PL_DATA_LEVELDB_DIR: /data
            PL_DATA_ATTACHMENTS_BACKEND: fs
            PL_DATA_ATTACHMENTS_DIR: /attachments
            PL_SERVER_CLIENT_URL: [redacted]
            PL_EMAIL_BACKEND: smtp
            PL_EMAIL_SMTP_HOST: smtp-relay.gmail.com
            PL_EMAIL_SMTP_PORT: 587
            PL_EMAIL_SMTP_IGNORE_TLS: true
            PL_EMAIL_SMTP_SECURE: true
            PL_EMAIL_SMTP_USER:
            PL_EMAIL_SMTP_PASSWORD:
            PL_EMAIL_SMTP_FROM: no-reply@[redacted]
...
```
