### ISSUE TITLE
Cannot Setup OICD even with All Environment Variables Set

### ISSUE THREAD

**Issue by Dan6erbond** [padloc/padloc#568]
I hope I'm not overlooking something blatantly obvious here, but I'm trying to configure OIDC with PadLoc. For reference, I am using a local deployment of Authentik, and configured the following environment variables in the server image:

```yml
            PL_AUTH_TYPES: openid
            PL_AUTH_OPENID_CLIENT_ID: <secret>
            PL_AUTH_OPENID_CLIENT_SECRET: <secret>
            PL_AUTH_OPENID_AUTHORIZATION_ENDPOINT: http://localhost:9000/application/o/authorize/
            PL_AUTH_OPENID_TOKEN_ENDPOINT: http://authentik-configuration-server-1:9000/application/o/token/
            PL_AUTH_OPENID_REDIRECT_URI: http://localhost:8080
```

To be honest, I'm not quite sure what the `PL_AUTH_OPENID_REDIRECT_URI` is for, but I have it configured to the PadLoc frontend location.

And the corresponding frontend environment:

```yml
            PL_AUTH_TYPES: openid
            PL_SERVER_URL: http://localhost:3000
```

Can someone point me in the right direction, on configuring OIDC for PadLoc with Docker?
