### ISSUE TITLE
Update self-hosting documentation

### ISSUE THREAD

**Issue by Z4Y** [padloc/padloc#605]
Barely any documentation has been updated to V4, there are no usable docker files, the docker-compose.yml is over a year old, and there aren't any particularly clear instructions on how to get up and running. As previously stated, the instructions that we do have at the moment are very outdated and I've had quite a bit of trouble trying to get myself a self-hosted instance.

**Comment by MaKleSoft** [comment]
It's true that the docs are a little sparse for v4. We're a small team so please bear with us. We'll get around to it, I promise :)

In the meantime, have you tried any of these examples? https://github.com/padloc/padloc/tree/main/docs/examples/hosting/docker

**Comment by BrunoBernardino** [comment]
As @MaKleSoft said, the official docs at https://docs.padloc.app/guides/self-host/ point to those 3 examples using Docker which are up-to-date and confirmed working by a few people already. Can you explain what have you tried, what have you found missing, and what errors you found? That should help us improve.

**Comment by BrunoBernardino** [comment]
Can you check the browser logs?

**Comment by BrunoBernardino** [comment]
Can you try accessing it via http://localhost:8080 instead (that's what that basic config expects)?

If you don't want to access it via localhost, you'll need to set `PL_PWA_URL` and `PL_SERVER_URL` properly for `pwa`, in your case, next to/below https://github.com/padloc/padloc/blob/main/docs/examples/hosting/docker/basic/docker-compose.yml#L26 and like:

```yml
pwa:
        image: padloc/pwa
        build:
            context: github.com/padloc/padloc.git#main
            dockerfile: Dockerfile-pwa
        environment:
            PL_SERVER_URL: http://10.1.1.34:3000
            PL_PWA_URL: http://10.1.1.34:8080
        ports:
            - 8080:8080
        restart: on-failure
```

Let me know if that helps.

**Comment by working-name** [comment]
I'm getting this when running the simple docker example:

```bash
Building server
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEIvCeE39/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
: exit status 128
ERROR: Service 'server' failed to build : Build failed
```

I can't tell if it's about my system or some docker image this is running in? I have openssl 1.1:

```
openssl is already the newest version (1.1.1f-1ubuntu2.16).
```

**Comment by working-name** [comment]
> Let me know if that helps.

It does not unfortunately. I tried switching to WSL2's internal IP, then windows machine's own IP, then localhost, then made up a domain `padloc.test` and mapped it to `127.0.0.1` and in all cases it fails, even when `localhost` matches.

Note that the `script-src blob:` value doesn't change from localhost no matter what you place in the docker-compose.yml

### padloc.test as `PL_SERVER_CLIENT_URL` and `PL_SERVER_URL`
```js
Refused to load the script 'http://padloc.test:8088/main.js' because it violates the following Content Security Policy directive: "script-src blob: http://localhost:8080/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

padloc.test/:1 Refused to load the image 'http://padloc.test:8088/favicon.png' because it violates the following Content Security Policy directive: "img-src http://localhost:8080/ blob: data: https://icons.duckduckgo.com".
```

### localhost as `PL_SERVER_CLIENT_URL` and `PL_SERVER_URL`

```js
Refused to load the script 'http://localhost:8088/main.js' because it violates the following Content Security Policy directive: "script-src blob: http://localhost:8080/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

localhost/:1 Refused to load manifest from 'http://localhost:8088/manifest.623e2268f17398ec7f19225e281e4056.json' because it violates the following Content Security Policy directive: "manifest-src http://localhost:8080/".

localhost/:1 Refused to load the image 'http://localhost:8088/favicon.png' because it violates the following Content Security Policy directive: "img-src http://localhost:8080/ blob: data: https://icons.duckduckgo.com".
```

**Comment by BrunoBernardino** [comment]
@working-name I'm not sure what to do about the IP matching in Windows, but as for the CSP error, what's used in it is `PL_PWA_URL`, not `PL_SERVER_URL`, and that's what I suggested you set above.

If you set that and it's not being picked up, can you share your full `docker-compose.yml` file?

**Comment by working-name** [comment]
> what's used in it is `PL_PWA_URL`, not `PL_SERVER_URL`, and that's what I suggested you set above.

Yes, I just figured it out: it was the port number. I mapped 8088 to internal 8080 and that's why the error. If I leave it on 8080 for both host and app then it's fine either with `PL_PWA_URL` set or without it. If I swap all `8080` ports in the docker-compose to `8088` the app still stubbornly tries to start on `8080` given its logs, and the browser gets an empty response.

```yml
version: "3.7"
services:
    server:
        image: padloc/server
        build:
            context: github.com/padloc/padloc.git#main
            dockerfile: Dockerfile-server
        environment:
            PL_DATA_BACKEND: leveldb
            PL_DATA_LEVELDB_DIR: /data
            PL_DATA_ATTACHMENTS_BACKEND: fs
            PL_DATA_ATTACHMENTS_DIR: /attachments
            PL_SERVER_CLIENT_URL: http://localhost:8088
        ports:
            - 3000:3000
        volumes:
            - attachments:/attachments
            - data:/data
        restart: unless-stopped
    pwa:
        image: padloc/pwa
        build:
            context: github.com/padloc/padloc.git#main
            dockerfile: Dockerfile-pwa
        environment:
            PL_SERVER_URL: http://localhost:3000
            #PL_PWA_URL: http://localhost:8088
        ports:
            - 8088:8088
        restart: on-failure
volumes:
    data:
    attachments:
```

With the above YML the app will initialize like so:

```bash
pwa_1     | > http-server ${PL_PWA_DIR:-dist} -s -p ${PL_PWA_PORT:-8080} --proxy ${PL_PWA_URL:-http://0.0.0.0:${PL_PWA_PORT:-8080}}?
```
