### ISSUE TITLE
Not opening anywhere except localhost:8080

### ISSUE THREAD

**Issue by AmoghSaxena** [padloc/padloc#631]
![image](https://user-images.githubusercontent.com/13078900/203014473-30c20b29-95e8-4cff-b6d9-f22ecf9ead1f.png)
It keeps on loading if I opening the UI with IP or Domain Name. 
But if I open it with localhost it is opening. 

Please help me to fix it.

**Comment by BrunoBernardino** [comment]
Hi @AmoghSaxena if you open the browser console you should see some errors. I'm going to take a guess that you built padloc for localhost, which means the CSP (Content-Security-Policy) tags will now allow loading the app in any other domain/IP/hostname. You need to build the app for the domain you want to use. You can use the `PL_PWA_URL` env var for it.

Let me know if that fixes it for you.

**Comment by AmoghSaxena** [comment]
![image](https://user-images.githubusercontent.com/13078900/203061645-4b8e2fbb-3987-4b35-8c67-88db092e8094.png)
I am doing that but still it's not opening...
![image](https://user-images.githubusercontent.com/13078900/203065421-2aea5579-64dc-4a44-9766-91f46a0ec3f5.png)

**Comment by BrunoBernardino** [comment]
What's the error showing in the browser console?

**Comment by AmoghSaxena** [comment]
![image](https://user-images.githubusercontent.com/13078900/203071023-0bf05d03-ea67-4292-923b-5262ec9d8a37.png)

@BrunoBernardino  Here is the consol output as I can see

**Comment by BrunoBernardino** [comment]
You can see in the log that the CSP directive states localhost and not the domain you had. Have you run `npm run build` with those environment variables? Or how are you deploying/running the app?

**Comment by AmoghSaxena** [comment]
@BrunoBernardino How can I build it? It's on docker. Please there is no clear document for docker deployment

**Comment by AmoghSaxena** [comment]
@BrunoBernardino I tried doing the same, nothing happened. It's still same with same logs

**Comment by BrunoBernardino** [comment]
Can you share your `docker-compose.yml` file contents? Something should've happened, like seeing the webpack build go on and such. Can you share the terminal output once you ran `docker-compose up -d --build`?

**Comment by AmoghSaxena** [comment]
### My docker-compose.yml
```
version: "3"
services:
    server:
        image: padloc/server
        container_name: padloc_server
        ports:
            - ${PL_SERVER_PORT:-3000}:3000
        volumes:
            # - ${PL_DB_DIR:-./db}:/data
            - /workstation/vault/db:/padloc/packages/server/data
            - ${PL_ATTACHMENTS_DIR:-./attachments}:/docs

    pwa:
        image: padloc/pwa
        container_name: padloc_pwa
        ports:
            - ${PL_PWA_PORT:-8080}:8080
        volumes:
            - ${PL_PWA_DIR:-./pwa}:/pwa

```

### My ENV File
```
# GENERAL SETTINGS
# ================
# URL that will resolve to the server instance
PL_SERVER_CLIENT_URL=https://crypt.amoghsaxena.com
PL_PWA_URL=https://crypt.amoghsaxena.com
# URL that will resolve to the web app
PL_SERVER_URL=https://server.amoghsaxena.com

# SERVER SETTINGS
# ===============
# Port the server instance will listen on
PL_SERVER_PORT=301
# Directory where database files will be stored
PL_DB_DIR=./db
# Directory where attachment files will be stored
PL_ATTACHMENTS_DIR=./attachments

# PWA SETTINGS
# ============
# Port the web app will be served from
PL_PWA_PORT=303
# Directory where the static code for the web app will be stored
PL_PWA_DIR=./pwa

# EMAIL SETTINGS <CHANGED>
# =============
# SMTP host
PL_EMAIL_SERVER=fsdafsdafsdfsd
# SMTP username
PL_EMAIL_USER=fdsfsdfas
# SMTP port
PL_EMAIL_PORT=fsadfsadfsa
# SMTP password
PL_EMAIL_PASSWORD=fsadfsadfas
# Always use TLS when sending emails
PL_EMAIL_SECURE=fsdfsdafsadf

# SSL SETTINGS
# ============
# The path to your ssl certificate
PL_SSL_CERT=./ssl/cert.pem
# The path to your ssl private key
PL_SSL_KEY=./ssl/key.pem
# Advanced configuration file
# PL_SSL_CONF=./ssl/ssl.conf
```
