### ISSUE TITLE
Cannot disable signup

### ISSUE THREAD

**Issue by somoit-JSP** [padloc/padloc#689]
Hi!
Im selfhosting Padloc v4.2.0. Maybe i doing something wrong, but im trying to disable signup by setting environment variable...

**PL_SERVER_DISABLE_SIGNUP=true**

... but it seems to have no effect. I have seen it in the example env file. Is it implemented? Is there any way to disable signup?
Thanks!

**Comment by BrunoBernardino** [comment]
@somoit-JSP thanks for reporting this, we'd need a bit more information. That env var should work, but it needs to be passed on to the server properly. Are you running it via `docker-compose up`, or some other way? If so, can you share your `docker-compose.yml` file or whatever docker configuration you've got?

**Comment by somoit-JSP** [comment]
Hi @BrunoBernardino.
Correct, im using docker-compose and env file contains more variables that are succesfully parsed and used.
These are the vars contained in my env file
Thanks!

`
PL_EMAIL_BACKEND=console

PL_EMAIL_BACKEND=smtp

PL_EMAIL_SMTP_HOST=smtp.mydomain.com

PL_EMAIL_SMTP_PORT=25

PL_EMAIL_SMTP_FROM="padloc@mydomain.com"

PL_DATA_BACKEND=leveldb

PL_DATA_LEVELDB_DIR=/data

PL_ATTACHMENTS_BACKEND=fs

PL_ATTACHMENTS_FS_DIR=/attachments

PL_SERVER_CLIENT_URL=https://padloc.mydomain.com

PL_SERVER_REPORT_ERRORS=email@mydomain.com

PL_SERVER_VERIFY_EMAIL_ON_SIGNUP=false

PL_SERVER_DISABLE_SIGNUP=true

PL_SERVER_ADMINS=email@mydomain.com

PL_SERVER_URL=https://padloc.mydomain.com

PL_PWA_URL=https://padloc.mydomain.com`

**Comment by somoit-JSP** [comment]
Sorry, i forgot. Here you have:

```
version: "3.7"
services:
    server:
        image: padloc/server
        env_file: ./env
        ports:
            - 127.0.0.1:3000:3000
        volumes:
            - ./attachments:/attachments
            - ./data:/data
        restart: unless-stopped
    pwa_custom:
        image: padloc/pwa
        env_file: ./env
        ports:
            - 127.0.0.1:8080:8080
        restart: on-failure
volumes:
    data:
    attachments:
```

**Comment by BrunoBernardino** [comment]
@somoit-JSP All looks good and you sent me down a rabbit whole, from which I'll need @MaKleSoft to help me get out of.

[This commit](https://github.com/padloc/padloc/commit/19d2b5e49ff82e999ca8164bcd78e85f77cb4361) enabled this feature. And it was merged as part of [this PR](https://github.com/padloc/padloc/pull/429).

However, by the time [v4.1.0 is released](https://github.com/padloc/padloc/pull/589), that commit/code is no longer there.

You can also see in [the history from the current `main` branch](https://github.com/padloc/padloc/commits/main?before=30ebb78768d4cfccdbf5f72bd51517c24334f874+35&branch=main&path%5B%5D=packages&path%5B%5D=core&path%5B%5D=src&path%5B%5D=error.ts&qualified_name=refs%2Fheads%2Fmain) that the commit with this feature isn't there, so I'm guessing this got lost somewhere with a force push? Or was it something else I'm missing?

**Comment by MaKleSoft** [comment]
Sorry for the late response! I think I started writing a response two weeks ago but forgot to send it 😅

The `PL_SERVER_DISABLE_SIGNUP` is no longer available and was basically superseded by the whole provisioning mechanism. Basically, you can now achieve the same thing by configuring the provisioning layer like so:

```
PL_PROVISIONING_BACKEND=basic
PL_PROVISIONING_BASIC_DEFAULT_STATUS=unprovisioned
```

This has the downside that in order to whitelist new users you basically have to edit their provisioning status to `active` manually. Let me know if you need help with that!

**Comment by BrunoBernardino** [comment]
I guess then we need to remove `PL_SERVER_DISABLE_SIGNUP` from [the example env](https://github.com/padloc/padloc/blob/main/docs/examples/config/example.env)

**Comment by hampoelz** [comment]
Is it by design that `PL_PROVISIONING_BASIC_DEFAULT_STATUS=unprovisioned` continues to ask non-existing accounts to verify their email as if a new account were being created? _(even if `PL_SERVER_VERIFY_EMAIL_ON_SIGNUP=false` is set)_

**Comment by magiceupho** [comment]
Hi,

@MaKleSoft I've tested this to variables but the signup is not disabled.
Here is my compose.yaml:
```
services:
  server:
    image: padloc/server
    container_name: padloc-server
    build:
      context: github.com/padloc/padloc.git#main
      dockerfile: Dockerfile-server
    env_file: ./.env
    ports:
      - 3000:3000
    volumes:
      - ./attachments:/attachments
      - ./data:/data
    restart: unless-stopped
    networks:
      - utils-network

  pwa:
    image: padloc/pwa
    container_name: padloc-pwa
    build:
      context: github.com/padloc/padloc.git#main
      dockerfile: Dockerfile-pwa
    env_file: ./.env
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - utils-network

networks:
  utils-network:
    external: true
```
Can you help me please ?

Regards
