### ISSUE TITLE
Admin Portal with Docker

### ISSUE THREAD

**Issue by Kruzerson** [padloc/padloc#727]
Hello. I couldn't find it in the documentation. I don't understand how to start Admin Portal with Docker compose. My configuration file looks like this, but I don't understand where to put the settings to start the Admin Portal. I am using nginx as a reverse proxy. Thanks for your help

```
version: "3.7"
services:
    server:
        image: padloc/server
        build:
            context: github.com/padloc/padloc.git#main
            dockerfile: Dockerfile-server
        environment:
            PL_DATA_BACKEND: leveldb
            PL_DATA_LEVELDB_DIR: /data
            PL_DATA_ATTACHMENTS_BACKEND: fs
            PL_DATA_ATTACHMENTS_DIR: /attachments
            PL_SERVER_CLIENT_URL: https://padloc.<domain>.com
            PL_EMAIL_BACKEND: smtp
            PL_EMAIL_SMTP_HOST: "mail.<domain>.com"
            PL_EMAIL_SMTP_PORT: 255
            PL_EMAIL_SMTP_SECURE: "false"
            PL_EMAIL_SMTP_IGNORE_TLS: "true"
            PL_EMAIL_SMTP_USER: "<user>"
            PL_EMAIL_SMTP_PASSWORD: "<password>"
            PL_EMAIL_SMTP_FROM: "<from>"
        expose:
            - 3000
        volumes:
            - attachments:/attachments
            - data:/data
        restart: unless-stopped

    pwa:
        image: padloc/pwa
        environment:
            PL_SERVER_URL: https://padloc.<domain>.com/server
            PL_PWA_URL: https://padloc.<domain>.com
            PL_PWA_PORT: 443
            PL_PWA_DISABLE_CSP: "true"
        build:
            context: github.com/padloc/padloc.git#main
            dockerfile: Dockerfile-pwa
        volumes:
            - pwa:/pwa
        command: ["build"]
        restart: on-failure

    nginx:
        image: nginx
        depends_on:
            - server
        restart: always
        volumes:
            - pwa:/pwa
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./ssl:/etc/nginx/ssl
        ports:
            - 80:80
            - 443:443
           
volumes:
    data:
    attachments:
    pwa:
```

**Comment by celevra** [comment]
my compose:

```
version: "3.7"
services:
    server:
        image: padloc/server
        build:
            context: github.com/padloc/padloc.git#main
            dockerfile: Dockerfile-server
        environment:
            PL_DATA_BACKEND: leveldb
            PL_DATA_LEVELDB_DIR: /data
            PL_DATA_ATTACHMENTS_BACKEND: fs
            PL_DATA_ATTACHMENTS_DIR: /attachments
            PL_SERVER_CLIENT_URL: http://localhost:8081
        ports:
            - 3000:3000
        volumes:
            - /docker/padloc/attachments:/attachments
            - /docker/padloc/data:/data
        restart: unless-stopped
    pwa:
        image: padloc/pwa
        build:
            context: github.com/padloc/padloc.git#main
            dockerfile: Dockerfile-pwa
        environment:
            PL_SERVER_URL: https://xxx/server
            PL_PWA_URL: https://xxx
        ports:
            - 8081:8080
        restart: unless-stopped
```

my nginx
```
  location / {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_pass http://127.0.0.1:8081;
    proxy_redirect off;
  }

  location /server {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_pass http://127.0.0.1:3000;
    proxy_redirect off;
  }
```
